let suggestions = [
    "Channel",
    "CodingLab",
    "CodingNepal",
    "YouTube",
    "YouTuber",
    "YouTube Channel",
    "Blogger",
    "Bollywood",
    "Vlogger",
    "Vechiles",
    "Facebook",
    "Freelancer",
    "Facebook Page",
    "Designer",
	"good web developer",
	"good wprker",
	"HHHH",
	"Animation in javascript",
	"Animation in css",
	"Effective workout in abs",
	"effice meaning in tamil",
	"effective workout in arms",
	"Essense meaning in tamil",
	"Organisation of fabevy",
	"oracle is the best?",
	"offer in javascript",
	"isolation in array value",
	"intialisation is what",
	"javascript in tamil",
	"jaguar car",
	"karaikudi in which district near",
	"kallanai whose period build",
	"lattitude formula",
	"lycra wear",
	"Man vs wild",
	"Manboo stick",
	"Nano engineer",
	"Naanee actor",
    "Developer",
    "Web Designer",
    "Web Developer",
    "Login Form in HTML & CSS",
    "How to learn HTML & CSS",
    "How to learn JavaScript",
    "How to became Freelancer",
    "How to became Web Designer",
    "How to start Gaming Channel",
    "How to start YouTube Channel",
    "What does HTML stands for?",
    "What does CSS stands for?",
];